version: '3.7'

x-common-variables: &common-variables
  DATABASES: ${DATABASES}
  SECRET_KEY: ${SECRET_KEY}
  REST_FRAMEWORK: ${REST_FRAMEWORK}
  DEBUG: ${DEBUG}
  SOCIAL_AUTH_GEOSECURE_DOMAIN: ${SOCIAL_AUTH_GEOSECURE_DOMAIN}
  SOCIAL_AUTH_GEOSECURE_KEY: ${SOCIAL_AUTH_GEOSECURE_KEY}
  SOCIAL_AUTH_GEOSECURE_SECRET: ${SOCIAL_AUTH_GEOSECURE_SECRET}
  SOCIAL_AUTH_GEOPLATFORM_DOMAIN: ${SOCIAL_AUTH_GEOPLATFORM_DOMAIN}
  SOCIAL_AUTH_GEOPLATFORM_KEY: ${SOCIAL_AUTH_GEOPLATFORM_KEY}
  SOCIAL_AUTH_GEOPLATFORM_SECRET: ${SOCIAL_AUTH_GEOPLATFORM_SECRET}
  SOCIAL_AUTH_GEOPLATFORM_PREAPPROVED_DOMAINS: ${SOCIAL_AUTH_GEOPLATFORM_PREAPPROVED_DOMAINS}
  SOCIAL_AUTH_GEOPLATFORM_UNKNOWN_REQUESTER_GROUP_ID: ${SOCIAL_AUTH_GEOPLATFORM_UNKNOWN_REQUESTER_GROUP_ID}
  SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS: ${SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS}
  INSTALLED_APPS: ${INSTALLED_APPS}
  ALLOWED_HOSTS: ${ALLOWED_HOSTS}
  CORS_ORIGIN_WHITELIST: ${CORS_ORIGIN_WHITELIST}
  CORS_ALLOW_CREDENTIALS: ${CORS_ALLOW_CREDENTIALS}
  CORS_MIDDLEWARE: ${CORS_MIDDLEWARE}
  DRF_RECAPTCHA_SECRET_KEY: ${DRF_RECAPTCHA_SECRET_KEY}
  DRF_RECAPTCHA_MINIMUM_SCORE: ${DRF_RECAPTCHA_MINIMUM_SCORE}
  CSRF_COOKIE_DOMAIN: ${CSRF_COOKIE_DOMAIN}
  CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
  HOST_ADDRESS: ${HOST_ADDRESS}
  COORDINATOR_ADMIN_GROUP_ID: ${COORDINATOR_ADMIN_GROUP_ID}
  SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
  SLACK_CHANNEL: ${SLACK_CHANNEL}
  INTERNAL_IPS: ${INTERNAL_IPS}
  SOCIAL_AUTH_REDIRECT_IS_HTTPS: ${SOCIAL_AUTH_REDIRECT_IS_HTTPS}

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      <<: *common-variables
